name: Publish Website Update

on:
  pull_request:
    branches:
      - new-actions

jobs:

  should-publish:
    uses: ./.github/workflows/should-publish.yml

  publish:
    needs: [should-publish]
    if: needs.should-publish.outputs.publish == 1
    - name: Show results
      run: |
        echo "Publish It!"
