name: Publish Website Update

on:
  pull_request:
    branches:
      - new-actions

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description for publish
        id: is-checked
        env:
          BODY: ${{ github.event.pull_request.body }}
        shell: bash
        run: |
          if [[ $BODY =~ "[x] Send Notifications To Group" ]]; then
            PUBLISH=1
          else
            PUBLISH=0
          fi
          echo "publish=$PUBLISH" >> "$GITHUB_OUTPUT"
      - name: Show results
        if: steps.is-checked.outputs.publush == '1'
        run: |
          echo "Publish It!"
