name: Publish Website Update

on:
  pull_request:
    branches:
      - new-actions

jobs:

  should-publish:
    uses: ./.github/workflows/should-publish.yml

  publish:
    needs: should-publish
    if: needs.should-publish.outputs.publish == 1
    uses: ./.github/workflows/slack-publish.yml
    secrets: inherit
