
on:
  workflow_call:

jobs:
  notify_slack:
    name: Notify Slack
    uses: slackapi/slack-github-action@v1.27.0
    with:
      channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
      slack-message: "Testing"
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
